[package]
name = "tentrackule-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
tracing = "0.1"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4"] }

tentrackule-shared = { path = "../shared" }
