[package]
name = "tentrackule-alert"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
thiserror = "2"

tentrackule-riot-api = { path = "../riot-api" }

[dev-dependencies]
serde_json = "1"
