name: CI Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Format check
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
        run: cargo fmt --all -- --check

      - name: Run tests
        run: cargo test --verbose --all --locked

      - name: Build
        if: github.ref == 'refs/heads/master'
        run: cargo build --verbose --release
